### ISSUE TITLE
Alternative method to add HTML Markup

### ISSUE THREAD

**Issue by connorcartwright** [ConnorCartwright/jquery-q-and-a-wp#10]
@AurelioDeRosa 

You mentioned an older way was to use a script tag:

```
<script id="template-modal" type="text/template">
    <div id="modal">
    <p>Hello <span id="name">Aurelio</span>!</p>
    </div>
</script>
```

And then access it in our .js like:

```
var code = $('#template-modal');

code
    .find('#name')
    .text('Aurelio');
```

I remember you mentioning there was a newer way - did we discuss that?

**Comment by AurelioDeRosa** [comment]
The other  approach is to use the [template element](https://developer.mozilla.org/en/docs/Web/HTML/Element/template).
