### ISSUE TITLE
Setup Browserify

### ISSUE THREAD

**Issue by connorcartwright** [ConnorCartwright/jquery-q-and-a-wp#7]

**Comment by connorcartwright** [comment]
Hey @AurelioDeRosa 

I've been looking through the [documentation](https://www.npmjs.com/package/grunt-browserify) for `grunt-browserify`.

I'm trying to understand where I would implement `browserify` - I know my two modal files `question-modal.js` and `embed-modal.js` both require the shared functions in `modal-shared.js` - is this where browserify comes into action?

**Comment by AurelioDeRosa** [comment]
Hi @ConnorCartwright.

That's exactly one of the main reason to use Browserify. I'd like to help you with this task and we can discuss what its benefits are and how to integrate it in our next call.

**Comment by connorcartwright** [comment]
Hey @AurelioDeRosa 

Just to make sure I have the right idea, when we use `browserify` will we no longer need to use the `concat` task?

I'm under the impression that `browserify` will build our `main.js` file containing all of the `modules` we define.

**Comment by AurelioDeRosa** [comment]
I confirm you won't need concat anymore.
